# --- This file contains the projects table data.

# Required Fields:
# - name
# - url

# Optional Fields:
# - state
# - engine
# - language[]
# - source
# - license

###########################################################
######################## Released #########################
###########################################################

[[projects]]
name = "Infiniminer"
url = "http://thesiteformerlyknownas.zachtronicsindustries.com/infiniminer/"
state = "Released"
note = "The game that (re)started it all."

[[projects]]
name = "Minecraft"
url = "https://www.minecraft.net/"
state = "Released"
source = "https://minecraft.wiki/w/Obfuscation_map"
language = ["Java"]
rendering = "Naive Baked Bloxel Mesh Rasterization"
storage = "[Multi-Level Grid](/wiki/datastructures/multi-level-grid) with Columns of [Chunks](/wiki/chunking)"

[[projects]]
name = "Teardown"
url = "https://www.teardowngame.com/"
state = "Released"
rendering = "Raytracing"

[[projects]]
name = "Astroneer"
url = "https://astroneer.space/"
state = "Released"

[[projects]]
name = "Deep Rock Galactic"
url = "https://www.deeprockgalactic.com/"
state = "Released"

[[projects]]
name = "Eco"
url = "https://play.eco/"
state = "Released"

[[projects]]
name = "No Man's Sky"
url = "https://www.nomanssky.com/"
state = "Released"

[[projects]]
name = "Space Engineers"
url = "https://www.spaceengineersgame.com/"
state = "Released"

[[projects]]
name = "Trove"
url = "https://www.trionworlds.com/trove/en/"
state = "Released"

[[projects]]
name = "Cube"
url = "http://cubeengine.com/"
state = "Released"

[[projects]]
name = "Cube 2: Sauerbraten"
url = "http://sauerbraten.org/"
state = "Released"

[[projects]]
name = "Minetest"
url = "http://minetest.net/"
state = "Released"
engine = "Using a [Fork of Irrlicht](https://github.com/minetest/irrlicht)"
language = ["C++", "Lua"]
source = "https://github.com/minetest/minetest/"
license = "LGPL v2.1+"
rendering = "Naive Bloxel Mesh Rasterization"
storage = "Grid of [Chunks](/wiki/chunking) stored in SQLite"

[[projects]]
name = "Simple Voxel Raycaster"
url = "https://github.com/clemdemort/simple-voxel-raycaster"
state = "Released"
language = ["C++", "GLSL"]
source = "https://github.com/clemdemort/simple-voxel-raycaster"
license = "GPL-3.0"

[[projects]]
name = "3079"
url = "https://store.steampowered.com/app/259620/3079__Block_Action_RPG/"
state = "Released"
language = ["Java"]
engine = "jMonkeyEngine"

[[projects]]
name = "Block Fortress: Empires"
url = "https://play.google.com/store/apps/details?id=com.foursakenmedia.blockfortressempires"
state = "Released"

[[projects]]
name = "BLOCKPOST"
url = "https://store.steampowered.com/app/706990/BLOCKPOST/"
state = "Released"

[[projects]]
name = "Qubicle"
url = "https://store.steampowered.com/app/454550/Qubicle_Voxel_Editor/"
state = "Released"

[[projects]]
name = "Boundless"
url = "https://playboundless.com/"
state = "Released"

[[projects]]
name = "Build A World EDU"
url = "https://edu.buildaworld.net/"
state = "Released"

[[projects]]
name = "Build & Shoot"
url = "https://www.buildandshoot.com/"
state = "Released"

[[projects]]
name = "Creativerse"
url = "https://creativersegame.com/"
state = "Released"

[[projects]]
name = "Synthetic World"
url = "https://www.staudsoft.com/"
state = "Released"

[[projects]]
name = "Staxel"
url = "https://playstaxel.com/"
state = "Released"

[[projects]]
name = "Murder Miners"
url = "http://jforcegames.com/"
state = "Released"

[[projects]]
name = "Lego Worlds"
url = "https://store.steampowered.com/app/332310/LEGO_Worlds/"
state = "Released"

[[projects]]
name = "Cubzh"
url = "https://cu.bzh"
state = "Released"
source = "https://github.com/cubzh/cubzh"
licence = "Apache-2.0"
languages = ["Lua", "C", "C++"]

[[projects]]
name = "7 Days To Die"
url = "https://7daystodie.com/"
state = "Released"

###########################################################
###################### Early Access #######################
###########################################################

[[projects]]
name = "Vintage Story"
url = "https://www.vintagestory.at/"
state = "Early Access"
language = ["C#"]
source = "https://github.com/anegostudios"

[[projects]]
name = "Colony Survival"
url = "https://store.steampowered.com/app/366090/Colony_Survival/"
state = "Early Access"
engine = "Unity3d"
language = ["C#"]

[[projects]]
name = "Sector's Edge"
url = "https://sectorsedge.com/s/i2s2"
state = "Early Access"
language = ["C#"]

[[projects]]
name = "Avoyd"
url = "https://www.avoyd.com/"
state = "Early Access"
language = ["C++"]
source = "https://www.enkisoftware.com/faq#engine"

[[projects]]
name = "Obsidian Prince"
url = "https://store.steampowered.com/app/1373260/Obsidian_Prince/"
state = "Early Access"
engine = "Unity3D"
language = ["C#"]

[[projects]]
name = "Brutal nature"
url = "https://www.brutalnature.com/"
state = "Early Access"

[[projects]]
name = "Empyrion"
url = "http://empyriongame.com/"
state = "Early Access"

[[projects]]
name = "Exotic Matter"
url = "https://exoticmatter.io/"
state = "Early Access"

[[projects]]
name = "FortressCraft Evolved"
url = "https://store.steampowered.com/app/254200/FortressCraft_Evolved/"
state = "Early Access"

[[projects]]
name = "Rising World"
url = "https://www.rising-world.net/"
state = "Early Access"

[[projects]]
name = "StarMade"
url = "https://www.star-made.org/"
state = "Early Access"

###########################################################
########################### Beta ##########################
###########################################################

[[projects]]
name = "Magica Voxel"
url = "https://ephtracy.github.io/"
state = "Beta"

[[projects]]
name = "Dual Universe"
url = "https://www.dualuniverse.game/"
state = "Beta"

[[projects]]
name = "UpvoidMiner"
url = "https://upvoid.com/miner/about/"
state = "Beta"

###########################################################
################### Active Development ####################
###########################################################

[[projects]]
name = "Veloren"
url = "https://veloren.net/"
state = "Active Dev."
source = "https://gitlab.com/veloren/veloren"
license = "GNU GPL 3.0"
language = ["Rust"]
rendering = "Rasterization"

[[projects]]
name = "Terasology"
url = "https://terasology.org/"
state = "Active Dev."
license = "Apache 2.0"
source = "https://github.com/MovingBlocks/Terasology"
language = ["Java"]
rendering = "Greedy Bloxel Mesh Rasterization"
storage = "[Multi-Level Grid](/wiki/datastructures/multi-level-grid) of [Chunks](/wiki/chunking)"

[[projects]]
name = "Gvox Engine"
url = "https://www.gaberundlett.com"
state = "Active Dev."
source = "https://github.com/GabeRundlett/gvox_engine"
language = ["C++", "GLSL"]
license = "MIT"
rendering = "Raytracing"
storage = "[Gvox meta-format library](https://github.com/GabeRundlett/gvox)"

[[projects]]
name = "vengi"
url = "https://vengi-voxel.github.io/vengi/"
state = "Active Dev."
language = ["C++", "Lua"]
source = "https://github.com/vengi-voxel/vengi"
license = "MIT"

[[projects]]
name = "Permille.io"
url = "https://permille.io/Voxels/Latest/"
state = "Active Dev."
language = ["Javascript"]
source = "https://github.com/Permille/Permille.io"
license = "CC BY-NC-SA 4.0"
rendering = "Raytracing"

[[projects]]
name = "Spacefarer"
url = "https://playspacefarer.com/"
state = "Active Dev."
engine = "Bevy"
language = ["Rust"]

[[projects]]
name = "Simple Voxel Tracer"
url = "https://github.com/Ciwiel3/SimpleVoxelTracer"
state = "Active Dev."
source = "https://github.com/Ciwiel3/SimpleVoxelTracer"
language = ["C", "GLSL"]
license = "MIT"
rendering = "Raytracing"

[[projects]]
name = "Gnome Tower"
url = "https://www.youtube.com/channel/UC6qe1IBLMBi0jqaec-Msxlw"
state = "Active Dev."
language = ["C++"]
rendering = "Rasterization"

[[projects]]
name = "Voxelman"
url = "https://github.com/MrSmith33/voxelman2"
state = "Active Dev."
language = ["D", "Vox"]
source = "https://github.com/MrSmith33/voxelman2"
license = "Boost"

[[projects]]
name = "Super Voxel World"
url = "https://svw.itch.io/super-voxel-world"
state = "Active Dev."
engine = "Unity3D"
language = ["C#"]

[[projects]]
name = "Qwy3"
url = "https://github.com/anima-libera/qwy3"
state = "Active Dev."
language = ["Rust", "WGSL"]
source = "https://github.com/anima-libera/qwy3"
license = "Apache-2.0"

[[projects]]
name = "Polygon Hell 4D"
url = "https://store.steampowered.com/app/2765940/Polygon_Hell_4D/"
state = "Active Dev."
language = ["C", "HLSL"]

[[projects]]
name = "Polaron World Engine"
url = "https://www.PolaronWorldEngine.com"
state = "Active Dev."
language = ["C++"]
license = "Commercial"

###########################################################
#################### Unknown Status #######################
###########################################################

[[projects]]
name = "Voxel Farm"
url = "https://www.voxelfarm.com/index.html"

[[projects]]
name = "FreeMiner"
url = "https://github.com/freeminer/freeminer"
source = "https://github.com/freeminer/freeminer"
license = "LGPL"
language = ["C++"]
engine = "Minetest"

[[projects]]
name = "Voxel Planet"
url = "https://www.youtube.com/user/voxelplanet/videos"

[[projects]]
name = "StoneQuest"
url = "https://www.stonequest.de/"

[[projects]]
name = "StarForge"
url = "http://www.starforge.com/"

[[projects]]
name = "Blackvoxel"
url = "https://www.blackvoxel.com/"
language = ["C++"]
license = "LGPL v3+"
source = "https://github.com/Blackvoxel/Blackvoxel"

[[projects]]
name = "Guncraft"
url = "https://www.exatogames.com/"

[[projects]]
name = "Kopatel Online"
url = "https://kopatel-online.tumblr.com/"

[[projects]]
name = "FinityWorlds"
url = "https://www.youtube.com/channel/UCw6nMILS3QcJRHTHCuZuchg"

[[projects]]
name = "Polyvox"
url = "http://www.volumesoffun.com/polyvox-about/"
license = "ZLIB"
source = "https://bitbucket.org/volumesoffun/polyvox/src/develop/"

[[projects]]
name = "Noa"
url = "https://github.com/fenomas/noa"
license = "MIT"
language = ["JS"]
source = "https://github.com/fenomas/noa"

[[projects]]
name = "Voxeliq"
url = "https://github.com/bonesoul/voxeliq"
license = "MS-PL"
source = "https://github.com/bonesoul/voxeliq"

[[projects]]
name = "Chunk Stories"
url = "http://chunkstories.xyz/"
license = "LGPL"
language = ["Kotlin"]
source = "https://github.com/Hugobros3/chunkstories"

[[projects]]
name = "Manic Digger"
url = "https://sourceforge.net/projects/manicdigger/"
license = "CC0"
language = ["C#"]
source = "https://github.com/manicdigger/manicdigger"

[[projects]]
name = "Sea Of Memes"
url = "https://github.com/mgoodfel/SeaOfMemes"
language = ["C"]
source = "https://github.com/mgoodfel/SeaOfMemes"

[[projects]]
name = "Voxelman"
url = "https://www.youtube.com/@andreypenechko5283"
license = "BSL-1.0"
language = ["D"]
source = "https://github.com/MrSmith33/voxelman"

[[projects]]
name = "VoxelsAndPortals"
url = "https://github.com/RileyA/VoxelsAndPortals"
license = "GPL-3.0"
language = ["C++", "C"]
source = "https://github.com/RileyA/VoxelsAndPortals"

[[projects]]
name = "MineHack"
url = "https://github.com/mikolalysenko/MineHack"
language = ["C++", "C", "JS", "F#"]
source = "https://github.com/mikolalysenko/MineHack"

[[projects]]
name = "Playform"
url = "http://playformdev.blogspot.com/"
license = "MIT"
language = ["Rust", "GLSL"]
source = "https://github.com/bfops/playform/"

[[projects]]
name = "BlokWorld"
url = "http://blokworld.forumotion.co.uk/"
language = ["VB.NET"]

[[projects]]
name = "UmbraTech"
url = "https://code.google.com/archive/p/umbratech/"
language = ["C#"]
source = "https://code.google.com/archive/p/umbratech/source"

[[projects]]
name = "CraftStudio"
url = "https://sparklinlabs.itch.io/craftstudio"
language = ["C#"]

[[projects]]
name = "Voxies"
url = "https://www.voxies.io/"

[[projects]]
name = "Mathcraft"
url = "https://github.com/Bunkerbewohner/Mathcraft"
source = "https://github.com/Bunkerbewohner/Mathcraft"
language = ["C#"]

[[projects]]
name = "Craft In Space"
url = "http://craftinspace.blogspot.com/"
language = ["C#"]

[[projects]]
name = "Minecraft-Plus-Plus"
url = "https://code.google.com/archive/p/minecraft-plus-plus/"
source = "https://code.google.com/archive/p/minecraft-plus-plus/source"
language = ["C++"]

[[projects]]
name = "mineworld2"
url = "https://code.google.com/archive/p/mineworld2/"
source = "https://code.google.com/archive/p/mineworld2/source"
license = "GPL-3.0"
language = ["C#"]

[[projects]]
name = "CraftMania"
url = "https://github.com/mcourteaux/CraftMania/"
source = "https://github.com/mcourteaux/CraftMania/"
language = ["Java"]

[[projects]]
name = "Mythruna"
url = "http://mythruna.com/"

[[projects]]
name = "PetraVis"
url = "http://steinkraft.net/"

[[projects]]
name = "Scrumbleship"
url = "https://scrumbleship.com/"
language = ["C"]

[[projects]]
name = "Sjoerd's Voxel Engine"
url = "https://github.com/sjoerdev/voxel-engine"
source = "https://github.com/sjoerdev/voxel-engine"
language = ["C#"]

[[projects]]
name = "sproxel"
url = "http://sproxel.blogspot.com/"
source = "https://code.google.com/archive/p/sproxel/"
license = "BSD-3.0"

[[projects]]
name = "Hexane"
url = "https://voxelphile.com"
source = "https://github.com/voxelphile/hexane"
language = ["Rust", "Glsl"]
