# --- This file contains the projects table data.

# Required Fields:
# - name
# - url

# Optional Fields:
# - state
# - engine
# - language[]
# - source
# - license

[[projects]]
name = "Infiniminer"
url = "http://thesiteformerlyknownas.zachtronicsindustries.com/infiniminer/"
state = "Released"
note = "The game that (re)started it all."

[[projects]]
name = "Minecraft"
url = "https://www.minecraft.net/"
state = "Released"
source = "https://minecraft.fandom.com/wiki/Obfuscation_map"
language = ["Java"]
rendering = "Naive Baked Bloxel Mesh Rasterization"
storage = "[Multi-Level Grid](/wiki/storage/multi-level-grid) with Columns of [Chunks](/wiki/storage/chunking)"

[[projects]]
name = "Teardown"
url = "https://www.teardowngame.com/"
state = "Early Access"
rendering = "Raytracing"

[[projects]]
name = "Magica Voxel"
url = "https://ephtracy.github.io/"

[[projects]]
name = "Vintage Story"
url = "https://www.vintagestory.at/"
state = "Early Access"
language = ["C#"]
source = "https://github.com/anegostudios"

[[projects]]
name = "Terasology"
url = "https://terasology.org/"
state = "Active Dev."
license = "Apache 2.0"
source = "https://github.com/MovingBlocks/Terasology"
language = ["Java"]
rendering = "Greedy Bloxel Mesh Rasterization"
storage = "[Multi-Level Grid](/wiki/storage/multi-level-grid) of [Chunks](/wiki/storage/chunking)"

[[projects]]
name = "Veloren"
url = "https://veloren.net/"
state = "Active Dev."
source = "https://gitlab.com/veloren/veloren"
license = "GNU GPL 3.0"
language = ["Rust"]
rendering = "Rasterization"

[[projects]]
name = "Minetest"
url = "http://minetest.net/"
state = "Released"
engine = "Using a [Fork of Irrlicht](https://github.com/minetest/irrlicht)"
language = ["C++", "Lua"]
source = "https://github.com/minetest/minetest/"
license = "LGPL v2.1+"
rendering = "Naive Bloxel Mesh Rasterization"
storage = "Grid of [Chunks](/wiki/storage/chunking) stored in SQLite"

[[projects]]
name = "Permille.io"
url = "https://permille.io/Voxels/Latest/"
state = "Active Dev."
language = ["Javascript"]
source = "https://github.com/Permille/Permille.io"
license = "CC BY-NC-SA 4.0"
rendering = "Raytracing"

[[projects]]
name = "Gnome Tower"
url = "https://www.youtube.com/channel/UC6qe1IBLMBi0jqaec-Msxlw"
state = "Active Dev."
language = ["C++"]
rendering = "Rasterization"

[[projects]]
name = "Voxelman"
url = "https://github.com/MrSmith33/voxelman2"
state = "Active Dev."
engine = "Vox"
language = ["D"]
source = "https://github.com/MrSmith33/voxelman2"
license = "Boost"

[[projects]]
name = "Dream Settler"
url = "dreamsettler.com"
state = "Active Dev."
engine = "Unreal Engine 4"

[[projects]]
name = "vengi"
url = "https://mgerhardy.github.io/vengi"
state = "Active Dev."
language = ["C++"]
source = "https://mgerhardy.github.io/vengi"
license = "MIT"

[[projects]]
name = "Colony Survival"
url = "https://store.steampowered.com/app/366090/Colony_Survival/"
state = "Early Access"
engine = "Unity3d"
language = ["C#"]

[[projects]]
name = "Sector's Edge"
url = "https://sectorsedge.com/s/i2s2"
state = "Early Access"
language = ["C#"]

[[projects]]
name = "Simple Voxel Raycaster"
url = "https://github.com/clemdemort/simple-voxel-raycaster"
state = "Released"
language = ["C++", "GLSL"]
source = "https://github.com/clemdemort/simple-voxel-raycaster"

[[projects]]
name = "3079"
url = "https://sites.google.com/site/3079game/"
state = "Released"
language = ["Java"]
engine = "jMonkeyEngine"

[[projects]]
name = "Avoyd"
url = "https://www.avoyd.com/"
state = "Early Access"
language = ["C++"]
source = "https://www.enkisoftware.com/faq#engine"

[[projects]]
name = "Blackvoxel"
url = "https://www.blackvoxel.com/"
language = ["C++"]
license = "LGPL v3+"
source = "https://github.com/Blackvoxel/Blackvoxel"

[[projects]]
name = "Block Fortress: Empires"
url = "https://play.google.com/store/apps/details?id=com.foursakenmedia.blockfortressempires"
state = "Released"

[[projects]]
name = "BLOCKPOST"
url = "https://store.steampowered.com/app/706990/BLOCKPOST/"
state = "Released"

[[projects]]
name = "Obsidian Prince"
url = "https://store.steampowered.com/app/1373260/Obsidian_Prince/"
state = "Early Access"
engine = "Unity3D"
language = ["C#"]

[[projects]]
name = "Boundless"
url = "https://playboundless.com/"
state = "Released"

[[projects]]
name = "Brutal nature"
url = "https://www.brutalnature.com/"
state = "Early Access"

[[projects]]
name = "Build A World EDU"
url = "https://edu.buildaworld.net/"
state = "Released"

[[projects]]
name = "Build & Shoot"
url = "https://www.buildandshoot.com/"
state = "Released"

[[projects]]
name = "Creativerse"
url = "https://creativersegame.com/"
state = "Released"

[[projects]]
name = "Cube"
url = "http://cubeengine.com/"
state = "Released"

[[projects]]
name = "Cube 2: Sauerbraten"
url = "http://sauerbraten.org/"
state = "Released"

[[projects]]
name = "Deep Rock Galactic"
url = "https://www.deeprockgalactic.com/"
state = "Released"

[[projects]]
name = "Dual Universe"
url = "https://www.dualuniverse.game/"
state = "Beta"

[[projects]]
name = "Eco"
url = "https://play.eco/"
state = "Released"

[[projects]]
name = "Empyrion"
url = "http://empyriongame.com/"
state = "Early Access"

[[projects]]
name = "Exotic Matter"
url = "https://exoticmatter.io/"
state = "Early Access"

[[projects]]
name = "FortressCraft Evolved"
url = "https://store.steampowered.com/app/254200/FortressCraft_Evolved/"
state = "Early Access"

[[projects]]
name = "Lego Worlds"
url = "https://store.steampowered.com/app/332310/LEGO_Worlds/"
state = "Released"

[[projects]]
name = "No Man's Sky"
url = "https://www.nomanssky.com/"
state = "Released"

[[projects]]
name = "Rising World"
url = "https://www.rising-world.net/"
state = "Early Access"

[[projects]]
name = "Space Engineers"
url = "https://www.spaceengineersgame.com/"
state = "Released"

[[projects]]
name = "StarMade"
url = "https://www.star-made.org/"
state = "Early Access"

[[projects]]
name = "Synthetic World"
url = "https://www.staudsoft.com/"
state = "Released"

[[projects]]
name = "Staxel"
url = "https://playstaxel.com/"
state = "Released"

[[projects]]
name = "Super Voxel World"
url = "https://svw.itch.io/super-voxel-world"
state = "Active Dev."
engine = "Unity3D"
language = ["C#"]

[[projects]]
name = "Trove"
url = "https://www.trionworlds.com/trove/en/"
state = "Released"

[[projects]]
name = "Voxel Farm"
url = "https://www.voxelfarm.com/index.html"

[[projects]]
name = "FreeMiner"
url = "https://github.com/freeminer/freeminer"
source = "https://github.com/freeminer/freeminer"
license = "LGPL"
language = ["C++"]
engine = "Minetest"

[[projects]]
name = "Voxel Planet"
url = "https://www.youtube.com/user/voxelplanet/videos"

[[projects]]
name = "UpvoidMiner"
url = "https://upvoid.com/miner/about/"
state = "Beta"

[[projects]]
name = "StoneQuest"
url = "https://www.stonequest.de/"

[[projects]]
name = "StarForge"
url = "http://www.starforge.com/"

[[projects]]
name = "Murder Miners"
url = "http://jforcegames.com/"
state = "Released"

[[projects]]
name = "Guncraft"
url = "https://www.exatogames.com/"

[[projects]]
name = "Kopatel Online"
url = "https://kopatel-online.tumblr.com/"

[[projects]]
name = "FinityWorlds"
url = "https://www.youtube.com/channel/UCw6nMILS3QcJRHTHCuZuchg"
